#Makefile for UVM Testbench - Lab 06

# SIMULATOR = Questa for Mentor's Questasim
# SIMULATOR = VCS for Synopsys's VCS

SIMULATOR = VCS

FSDB_PATH=/home/cad/eda/SYNOPSYS/VERDI_2022/verdi/T-2022.06-SP1/share/PLI/VCS/LINUX64
SVTB3= ../tb/router_intf.sv
RTL= ../rtl/*
work= work #library name
SVTB1= ../tb/top.sv
INC = +incdir+../tb +incdir+../test +incdir+../ip_agt_top +incdir+../op_agt_top 
SVTB2 = ../test/router_test_pkg.sv
VSIMOPT= -vopt -voptargs=+acc 
VSIMCOV= -coverage -sva 
VSIMBATCH1= -c -do  " log -r /* ;coverage save -onexit mem_cov1;run -all; exit"
VSIMBATCH2= -c -do  " log -r /* ;coverage save -onexit mem_cov2;run -all; exit"
VSIMBATCH3= -c -do  " log -r /* ;coverage save -onexit mem_cov3;run -all; exit"
VSIMBATCH4= -c -do  " log -r /* ;coverage save -onexit mem_cov4;run -all; exit"


help:
	@echo =============================================================================================================
	@echo "! USAGE   	--  make target                             										!"
	@echo "! clean   	=>  clean the earlier log and intermediate files.       								!"
	@echo "! sv_cmp    	=>  Create library and compile the code.                   								!"
	@echo "! run_test	=>  clean, compile & run the simulation for ram_signle_adddr_test in batch mode.		!" 
	@echo "! run_test1	=>  clean, compile & run the simulation for ram_ten_addr_test in batch mode.			!" 
	@echo "! run_test2	=>  clean, compile & run the simulation for ram_odd_addr_test in batch mode.			!"
	@echo "! run_test3	=>  clean, compile & run the simulation for ram_even_addr_test in batch mode.		!" 
	@echo "! view_wave1 =>  To view the waveform of ram_signle_addr_test                                                    !"
	@echo "! view_wave2 =>  To view the waveform of ram_ten_addr_test                                                       !" 
	@echo "! view_wave3 =>  To view the waveform of ram_odd_addr_test                                                       !" 
	@echo "! view_wave4 =>  To view the waveform of ram_even_addr_test                                                      !" 
	@echo ====================================================================================================================

clean : clean_$(SIMULATOR)
sv_cmp : sv_cmp_$(SIMULATOR)
run_test : run_test_$(SIMULATOR)
run_test1 : run_test1_$(SIMULATOR)
run_test2 : run_test2_$(SIMULATOR)
run_test3 : run_test3_$(SIMULATOR)
view_wave1 : view_wave1_$(SIMULATOR)
view_wave2 : view_wave2_$(SIMULATOR)
view_wave3 : view_wave3_$(SIMULATOR)
view_wave4 : view_wave4_$(SIMULATOR)

# ----------------------------- Start of Definitions for Mentor's Questa Specific Targets -------------------------------#

sv_cmp_Questa:
	vlib $(work)
	vmap work $(work)
	vlog -work $(work) $(RTL) $(SVTB3) $(INC) $(SVTB2) $(SVTB1) 	
	
run_test_Questa: clean sv_cmp
	vsim  $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH1)  -wlf wave.wlf -l test1.log  -sv_seed random  work.top 
	
run_test1_Questa: clean sv_cmp
	vsim  $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH2)  -wlf wave1.wlf -l test2.log  -sv_seed random  work.top 
	
run_test2_Questa: clean sv_cmp
	vsim  $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH3)  -wlf wave2.wlf -l test3.log  -sv_seed random  work.top 
	
run_test3_Questa: clean sv_cmp
	vsim  $(VSIMOPT) $(VSIMCOV) $(VSIMBATCH4)  -wlf wave3.wlf -l test4.log  -sv_seed random  work.top 
	
clean_Questa: 
	rm -rf transcript* *log* fcover* covhtml* mem_cov* *.wlf modelsim.ini work
	clear


view_wave1_Questa: 
	vsim -view wave.wlf

view_wave2_Questa: 
	vsim -view wave1.wlf

view_wave3_Questa: 
	vsim -view wave2.wlf

view_wave4_Questa: 
	vsim -view wave3.wlf






# ----------------------------- End of Definitions for Mentor's Questa Specific Targets -------------------------------#

# ----------------------------- Start of Definitions for Synopsys's VCS Specific Targets -------------------------------#

sv_cmp_VCS:
	vcs -l vcs.log -timescale=1ns/1ps  -sverilog -ntb_opts uvm -debug_access+all -full64 -kdb -lca -P $(FSDB_PATH)/novas.tab $(FSDB_PATH)/pli.a $(RTL)  $(SVTB3) $(INC) $(SVTB2) $(SVTB1) 
	      
run_test_VCS:  sv_cmp_VCS
	./simv -a vcs.log +fsdbfile+wave.fsdb -cm_dir ./mem_cov1 +ntb_random_seed_automatic +UVM_TESTNAME=small_pkt_test
	urg -dir mem_cov1.vdb -format both -report urgReport1

run_test1_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave1.fsdb -cm_dir ./mem_cov2 +ntb_random_seed_automatic +UVM_TESTNAME=medium_pkt_test	
	urg -dir mem_cov2.vdb -format both -report urgReport2

run_test2_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave2.fsdb -cm_dir ./mem_cov3 +ntb_random_seed_automatic +UVM_TESTNAME=large_pkt_test
	urg -dir mem_cov3.vdb -format both -report urgReport3

run_test3_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave3.fsdb -cm_dir ./mem_cov4 +ntb_random_seed_automatic +UVM_TESTNAME=error_pkt_test 	
	urg -dir mem_cov4.vdb -format both -report urgReport4

run_test4_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave4.fsdb -cm_dir ./mem_cov5 +ntb_random_seed_automatic +UVM_TESTNAME=large_rst_pkt_test 	
	urg -dir mem_cov5.vdb -format both -report urgReport5

run_test5_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave5.fsdb -cm_dir ./mem_cov6 +ntb_random_seed_automatic +UVM_TESTNAME=small_pkt0_test 	
	urg -dir mem_cov6.vdb -format both -report urgReport6

run_test6_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave6.fsdb -cm_dir ./mem_cov7 +ntb_random_seed_automatic +UVM_TESTNAME=small_pkt1_test 	
	urg -dir mem_cov7.vdb -format both -report urgReport7

run_test7_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave7.fsdb -cm_dir ./mem_cov8 +ntb_random_seed_automatic +UVM_TESTNAME=small_pkt2_test 	
	urg -dir mem_cov8.vdb -format both -report urgReport8


run_test8_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave8.fsdb -cm_dir ./mem_cov9 +ntb_random_seed_automatic +UVM_TESTNAME=medium_pkt0_test 	
	urg -dir mem_cov9.vdb -format both -report urgReport9

run_test9_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave9.fsdb -cm_dir ./mem_cov10 +ntb_random_seed_automatic +UVM_TESTNAME=medium_pkt1_test 	
	urg -dir mem_cov10.vdb -format both -report urgReport10

run_test10_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave10.fsdb -cm_dir ./mem_cov11 +ntb_random_seed_automatic +UVM_TESTNAME=medium_pkt2_test 	
	urg -dir mem_cov11.vdb -format both -report urgReport11

run_test11_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave11.fsdb -cm_dir ./mem_cov12 +ntb_random_seed_automatic +UVM_TESTNAME=large_pkt0_test 	
	urg -dir mem_cov12.vdb -format both -report urgReport12

run_test12_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave12.fsdb -cm_dir ./mem_cov13 +ntb_random_seed_automatic +UVM_TESTNAME=large_pkt1_test 	
	urg -dir mem_cov13.vdb -format both -report urgReport13

run_test13_VCS: sv_cmp_VCS	
	./simv -a vcs.log +fsdbfile+wave13.fsdb -cm_dir ./mem_cov14 +ntb_random_seed_automatic +UVM_TESTNAME=large_pkt2_test 	
	urg -dir mem_cov14.vdb -format both -report urgReport14






report_VCS:
	urg -dir mem_cov1.vdb mem_cov2.vdb mem_cov3.vdb mem_cov4.vdb mem_cov5.vdb mem_cov6.vdb mem_cov7.vdb mem_cov8.vdb mem_cov9.vdb mem_cov10 mem_cov11.vdb mem_cov12.vdb mem_cov13.vdb mem_cov14.vdb .vdb -dbname merged_dir/merged_test -format both -report urgReport

regress_VCS: clean_VCS sv_cmp_VCS run_test_VCS run_test1_VCS run_test2_VCS run_test3_VCS run_test4_VCS run_test5_VCS run_test6_VCS run_test7_VCS run_test8_VCS run_test9_VCS run_test10_VCS run_test11_VCS run_test12_VCS run_test13_VCS report_VCS

cov_VCS:
	verdi -cov -covdir merged_dir.vdb
	
clean_VCS:
	rm -rf simv* csrc* *.tmp *.vpd *.vdb *.key *.log *hdrs.h *.fsdb verdi*
	clear

view_wave1_VCS: 
	verdi -ssf wave.fsdb
        
view_wave2_VCS: 
	verdi -ssf wave1.fsdb

view_wave3_VCS: 
	verdi -ssf wave2.fsdb

view_wave4_VCS: 
	verdi -ssf wave3.fsdb   

view_wave5_VCS: 
	verdi -ssf wave4.fsdb

# ----------------------------- END of Definitions for Synopsys's VCS Specific Targets -------------------------------#
